:jbake-title: Architekturentscheidungen
:jbake-type: page_toc
:jbake-status: published
:jbake-menu: arc42
:jbake-order: 9
:filename: /chapters/09_architecture_decisions.adoc
ifndef::imagesdir[:imagesdir: ../../images]

:toc:


[[section-design-decisions]]
== Architekturentscheidungen

ifdef::arc42help[]
[role="arc42help"]
****
.Inhalt
Wichtige, teure, große oder riskante Architektur- oder Entwurfsentscheidungen inklusive der jeweiligen Begründungen.
Mit "Entscheidungen" meinen wir hier die Auswahl einer von mehreren Alternativen unter vorgegebenen Kriterien.

Wägen Sie ab, inwiefern Sie Entscheidungen hier zentral beschreiben, oder wo eine lokale Beschreibung (z.B. in der Whitebox-Sicht von Bausteinen) sinnvoller ist.
Vermeiden Sie Redundanz.
Verweisen Sie evtl. auf Abschnitt 4, wo schon grundlegende strategische Entscheidungen beschrieben wurden.

.Motivation
Stakeholder des Systems sollten wichtige Entscheidungen verstehen und nachvollziehen können.

.Form
Verschiedene Möglichkeiten:

* ADR (https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions[Documenting Architecture Decisions]) für jede wichtige Entscheidung
* Liste oder Tabelle, nach Wichtigkeit und Tragweite der Entscheidungen geordnet
* ausführlicher in Form einzelner Unterkapitel je Entscheidung

.Weiterführende Informationen

Siehe https://docs.arc42.org/section-9/[Architekturentscheidungen] in der arc42 Dokumentation (auf Englisch!).
Dort finden Sie Links und Beispiele zum Thema ADR.

****
endif::arc42help[]

=== Übersicht der Entscheidungen

Jede Entscheidung ist ein ADR nach Nygard mit einer 3-Punkt-Pugh-Matrix. Quelle ist die Serie "Wir bauen eine Software-Architektur" von software-architektur.tv, Folgen 111 bis 113. Zeitmarken verweisen auf die jeweilige Folge.

[cols="1,4,2"]
|===
| ADR | Titel | Status

| <<adr-001>> | Nutzerverwaltung und Login über den Webshop | Accepted
|===

include::../adr/ADR-001-nutzerverwaltung-webshop.adoc[leveloffset=+1]
